modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="authmod"
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="authMod"
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/authmod"#optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
# credits="Thanks for this example mod goes to Java" #optional

authors="Chocorean, mcdostone"
# The description text for the mod (multi line!) (#mandatory)
description='''
'''
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
